window.DAILY_QUOTES = [
  {
    id: "jobs-stay-hungry",
    person: "Steve Jobs",
    role: "Apple 共同創業者",
    initials: "SJ",
    category: "craft",
    accent: "#17665d",
    quote: "Stay hungry. Stay foolish.",
    translation: "満足しきらず、常識に収まりきらない姿勢を持ち続ける。",
    bio: "Apple、NeXT、Pixarを通じて、技術とデザインを結びつけた起業家。2005年のスタンフォード大学卒業式スピーチでは、点と点を後からつなぐこと、失敗後にもう一度作ること、自分の時間を生きることを語った。",
    action: "今日やることを1つだけ選び、完成度よりもまず着手を優先する。",
    sourceTitle: "Stanford News: Steve Jobs' 2005 Stanford Commencement Address",
    sourceUrl: "https://news.stanford.edu/stories/2005/06/youve-got-find-love-jobs-says"
  },
  {
    id: "musk-failure-option",
    person: "Elon Musk",
    role: "Tesla / SpaceX 起業家",
    initials: "EM",
    category: "startup",
    accent: "#315f8d",
    quote: "Failure is an option here.",
    translation: "挑戦しているなら、失敗は選択肢の中にある。",
    bio: "PayPal、SpaceX、Teslaなどで、既存産業の前提を疑う事業を進めてきた起業家。失敗を避けるより、試行の速度を上げる姿勢が強い。",
    action: "失敗しても被害が小さい実験を1つ決め、今日中に試す。",
    sourceTitle: "Entrepreneur: Elon Musk quotes on innovation",
    sourceUrl: "https://www.entrepreneur.com/leadership/50-innovation-and-success-quotes-from-spacex-founder-elon/244515"
  },
  {
    id: "bezos-day-one",
    person: "Jeff Bezos",
    role: "Amazon 創業者",
    initials: "JB",
    category: "business",
    accent: "#bd6448",
    quote: "It remains Day 1.",
    translation: "成功後も、創業初日の緊張感で考える。",
    bio: "Amazonをオンライン書店から巨大なテクノロジー企業へ育てた創業者。株主向け書簡では、顧客中心、長期思考、速い意思決定を繰り返し重視している。",
    action: "今の作業を、最初の顧客に届けるつもりで1か所だけ改善する。",
    sourceTitle: "Amazon 1997 Letter to Shareholders",
    sourceUrl: "https://ir.aboutamazon.com/annual-reports-proxies-and-shareholder-letters/default.aspx"
  },
  {
    id: "ford-think",
    person: "Henry Ford",
    role: "Ford Motor Company 創業者",
    initials: "HF",
    category: "business",
    accent: "#17665d",
    quote: "Whether you think you can, or you think you can't, you're right.",
    translation: "できると思うか、できないと思うか。その前提が行動を決める。",
    bio: "自動車の大量生産を広げ、製造と労働の仕組みに大きな影響を与えた実業家。思い込みが行動量を変えることを示す言葉として広く知られる。",
    action: "今日の自分の言い訳を1つ書き出し、反対の前提で小さく動く。",
    sourceTitle: "The Henry Ford: Henry Ford quotes",
    sourceUrl: "https://www.thehenryford.org/collections-and-research/digital-collections/artifact/255228/"
  },
  {
    id: "edison-perspiration",
    person: "Thomas Edison",
    role: "発明家 / 起業家",
    initials: "TE",
    category: "resilience",
    accent: "#b6842f",
    quote: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    translation: "ひらめきだけでは足りない。ほとんどは手を動かす時間で決まる。",
    bio: "蓄音機、電球、映画技術などの発明と事業化で知られる人物。研究所を組織化し、発明を継続的に生む仕組みを作った。",
    action: "15分だけ、考える時間ではなく作る時間を確保する。",
    sourceTitle: "Thomas Edison National Historical Park",
    sourceUrl: "https://www.nps.gov/edis/index.htm"
  },
  {
    id: "buffett-value",
    person: "Warren Buffett",
    role: "Berkshire Hathaway 投資家",
    initials: "WB",
    category: "business",
    accent: "#315f8d",
    quote: "Price is what you pay. Value is what you get.",
    translation: "払う金額ではなく、得られる価値で判断する。",
    bio: "長期投資で知られる投資家・経営者。短期の値動きより、事業の本質的な価値を見続ける姿勢で知られる。",
    action: "今日の時間の使い方を、価格ではなく価値で1つ見直す。",
    sourceTitle: "Berkshire Hathaway shareholder letters",
    sourceUrl: "https://www.berkshirehathaway.com/letters/letters.html"
  },
  {
    id: "paul-graham-users",
    person: "Paul Graham",
    role: "Y Combinator 共同創業者",
    initials: "PG",
    category: "startup",
    accent: "#17665d",
    quote: "Make something people want.",
    translation: "人が本当に欲しがるものを作る。",
    bio: "Viawebを創業し、後にY Combinatorを共同創業した起業家・投資家。スタートアップに対して、抽象論よりユーザーの欲求に向き合うことを説いている。",
    action: "自分の作品やサービスについて、使う人の困りごとを1つだけ書く。",
    sourceTitle: "Y Combinator: Make something people want",
    sourceUrl: "https://www.ycombinator.com/"
  },
  {
    id: "reid-hoffman-jump",
    person: "Reid Hoffman",
    role: "LinkedIn 共同創業者",
    initials: "RH",
    category: "startup",
    accent: "#bd6448",
    quote: "If you are not embarrassed by the first version of your product, you've launched too late.",
    translation: "最初の版が恥ずかしいくらいでなければ、公開が遅すぎる。",
    bio: "LinkedInを共同創業し、PayPalにも関わった起業家・投資家。完成を待ちすぎず、早く出して学ぶ考え方を象徴する言葉で知られる。",
    action: "未完成でも人に見せられる最小の形を1つ作る。",
    sourceTitle: "LinkedIn: Reid Hoffman startup advice",
    sourceUrl: "https://www.linkedin.com/pulse/20130614122653-1213-if-you-re-not-embarrassed-by-your-first-product-release-you-ve-launched-too-late/"
  },
  {
    id: "drucker-effective",
    person: "Peter Drucker",
    role: "経営学者",
    initials: "PD",
    category: "business",
    accent: "#315f8d",
    quote: "There is nothing so useless as doing efficiently that which should not be done at all.",
    translation: "やるべきでないことを効率よくやっても意味がない。",
    bio: "現代経営学に大きな影響を与えた思想家。成果を出すには、速さよりも何に集中するかを見極める必要があると説いた。",
    action: "今日の予定から、やらなくていい作業を1つ消す。",
    sourceTitle: "Drucker Institute: Peter Drucker quotes",
    sourceUrl: "https://www.drucker.institute/thedx/there-is-nothing-so-useless-as-doing-efficiently-that-which-should-not-be-done-at-all/"
  },
  {
    id: "matsushita-path",
    person: "松下幸之助",
    role: "パナソニック創業者",
    initials: "松",
    category: "business",
    accent: "#17665d",
    quote: "道をひらく。",
    translation: "困難の中でも、自分の進む道は自分で作る。",
    bio: "松下電器を創業し、日本の代表的な経営者として知られる人物。著書『道をひらく』は、仕事と人生の姿勢を短い文章で伝えている。",
    action: "止まっている課題に対して、相談する・調べる・試すのどれか1つを選ぶ。",
    sourceTitle: "PHP研究所: 松下幸之助『道をひらく』",
    sourceUrl: "https://www.php.co.jp/books/detail.php?isbn=978-4-569-53407-7"
  },
  {
    id: "inaba-kyocera",
    person: "稲盛和夫",
    role: "京セラ創業者",
    initials: "稲",
    category: "business",
    accent: "#b6842f",
    quote: "動機善なりや、私心なかりしか。",
    translation: "その挑戦の動機は善いものか。自分本位だけになっていないか。",
    bio: "京セラとKDDIを創業し、JAL再建にも関わった経営者。判断の軸として、能力だけでなく心のあり方を重視した。",
    action: "今の目標が誰の役に立つのかを1行で書く。",
    sourceTitle: "京セラ: 稲盛和夫オフィシャルサイト",
    sourceUrl: "https://www.kyocera.co.jp/inamori/"
  },
  {
    id: "honda-action",
    person: "本田宗一郎",
    role: "Honda 創業者",
    initials: "本",
    category: "craft",
    accent: "#bd6448",
    quote: "チャレンジして失敗を恐れるよりも、何もしないことを恐れろ。",
    translation: "失敗よりも、動かないまま終わることを避ける。",
    bio: "町工場からHondaを世界的メーカーへ育てた技術者・起業家。現場で試し、失敗から改良する姿勢で知られる。",
    action: "今日、怖くて後回しにしている連絡・公開・試作を1つ進める。",
    sourceTitle: "Honda: 本田宗一郎について",
    sourceUrl: "https://global.honda/jp/guide/history-digest/founder/"
  },
  {
    id: "shibusawa-ronogo",
    person: "渋沢栄一",
    role: "実業家",
    initials: "渋",
    category: "business",
    accent: "#315f8d",
    quote: "論語と算盤。",
    translation: "利益と倫理を分けずに考える。",
    bio: "多くの企業設立に関わった日本近代経済の重要人物。事業を大きくするだけでなく、社会にとって正しい利益のあり方を説いた。",
    action: "今日の判断で、短期利益と信頼のどちらを優先すべきか確認する。",
    sourceTitle: "渋沢栄一記念財団",
    sourceUrl: "https://www.shibusawa.or.jp/"
  },
  {
    id: "oprah-luck",
    person: "Oprah Winfrey",
    role: "メディア起業家",
    initials: "OW",
    category: "resilience",
    accent: "#17665d",
    quote: "Luck is preparation meeting opportunity.",
    translation: "幸運は、準備が機会に出会ったときに生まれる。",
    bio: "テレビ番組、出版、メディア事業で大きな影響力を持つ起業家。機会を待つだけでなく、受け取れる状態を作る姿勢が伝わる。",
    action: "次のチャンスが来たときに必要な準備を1つだけ進める。",
    sourceTitle: "Oprah.com: Oprah quotes",
    sourceUrl: "https://www.oprah.com/"
  },
  {
    id: "arianna-failure",
    person: "Arianna Huffington",
    role: "HuffPost 共同創業者",
    initials: "AH",
    category: "resilience",
    accent: "#bd6448",
    quote: "Failure is not the opposite of success; it's part of success.",
    translation: "失敗は成功の反対ではなく、成功の一部である。",
    bio: "HuffPostを共同創業し、後にウェルビーイング領域でも事業を展開。失敗を終点ではなく学習過程として扱う考え方を発信している。",
    action: "最近の失敗を1つ選び、そこから次に変えることを1行で書く。",
    sourceTitle: "Thrive Global: Arianna Huffington",
    sourceUrl: "https://thriveglobal.com/authors/arianna-huffington/"
  },
  {
    id: "maya-angelou-courage",
    person: "Maya Angelou",
    role: "作家 / 活動家",
    initials: "MA",
    category: "resilience",
    accent: "#b6842f",
    quote: "Courage is the most important of all the virtues.",
    translation: "勇気がなければ、他の美徳を実行できない。",
    bio: "作家、詩人、活動家として多くの人に影響を与えた人物。自分の声を持ち、困難の中で尊厳を保つ姿勢が支持されている。",
    action: "少し勇気が必要な選択を1つだけ今日の予定に入れる。",
    sourceTitle: "Maya Angelou official site",
    sourceUrl: "https://www.mayaangelou.com/"
  },
  {
    id: "kennedy-moon",
    person: "John F. Kennedy",
    role: "第35代アメリカ大統領",
    initials: "JFK",
    category: "resilience",
    accent: "#315f8d",
    quote: "We choose to go to the Moon.",
    translation: "難しいからこそ、挑戦する対象を選ぶ。",
    bio: "1962年のライス大学演説で、月へ行くという大きな目標を掲げた。困難な目標が人と組織の能力を引き出す例として語られる。",
    action: "今の自分にとって少し大きい目標を、具体的な1文にする。",
    sourceTitle: "NASA: John F. Kennedy Moon Speech",
    sourceUrl: "https://www.nasa.gov/history/john-f-kennedys-moon-speech-rice-stadium/"
  },
  {
    id: "mandela-impossible",
    person: "Nelson Mandela",
    role: "南アフリカ元大統領",
    initials: "NM",
    category: "resilience",
    accent: "#17665d",
    quote: "It always seems impossible until it's done.",
    translation: "成し遂げるまでは、いつも不可能に見える。",
    bio: "長い投獄を経て、南アフリカの民主化と和解を進めた指導者。長期の困難に耐え、状況を変える象徴的な存在。",
    action: "不可能に見えることを、今日できる5分の行動に分解する。",
    sourceTitle: "Nelson Mandela Foundation",
    sourceUrl: "https://www.nelsonmandela.org/"
  },
  {
    id: "twain-secret",
    person: "Mark Twain",
    role: "作家 / 講演家",
    initials: "MT",
    category: "craft",
    accent: "#bd6448",
    quote: "The secret of getting ahead is getting started.",
    translation: "前に進む秘訣は、まず始めること。",
    bio: "アメリカ文学を代表する作家。鋭い観察と言葉で、行動や人間心理について多くの示唆を残した。",
    action: "先延ばししている作業を、タイマー5分で始める。",
    sourceTitle: "The Mark Twain House & Museum",
    sourceUrl: "https://marktwainhouse.org/"
  },
  {
    id: "picasso-inspiration",
    person: "Pablo Picasso",
    role: "画家 / クリエイター",
    initials: "PP",
    category: "craft",
    accent: "#315f8d",
    quote: "Inspiration exists, but it has to find you working.",
    translation: "ひらめきは存在する。ただし、働いている人のところに来る。",
    bio: "20世紀美術に大きな影響を与えた画家。多作で、変化を恐れず表現を更新し続けた創作者として知られる。",
    action: "気分が乗るのを待たず、作品づくりを10分だけ進める。",
    sourceTitle: "Museu Picasso Barcelona",
    sourceUrl: "https://museupicassobcn.cat/en"
  },
  {
    id: "lincoln-prepare",
    person: "Abraham Lincoln",
    role: "第16代アメリカ大統領",
    initials: "AL",
    category: "resilience",
    accent: "#17665d",
    quote: "I will prepare and someday my chance will come.",
    translation: "準備を続ければ、いつか機会が来る。",
    bio: "独学で法律を学び、大統領として南北戦争期を率いた人物。長い準備と粘り強さの象徴として語られる。",
    action: "まだ成果が見えない努力を1つ、今日の予定に残す。",
    sourceTitle: "Abraham Lincoln Presidential Library and Museum",
    sourceUrl: "https://presidentlincoln.illinois.gov/"
  },
  {
    id: "carnegie-team",
    person: "Andrew Carnegie",
    role: "実業家 / 慈善家",
    initials: "AC",
    category: "business",
    accent: "#b6842f",
    quote: "No person will make a great business who wants to do it all himself.",
    translation: "すべてを自分だけでやろうとする人は、大きな事業を作れない。",
    bio: "鉄鋼業で成功し、後に図書館などへの寄付で知られた実業家。事業を伸ばすには、人を信じて任せる力が必要だと考えた。",
    action: "自分だけで抱えている作業を1つ、人に相談する形に変える。",
    sourceTitle: "Carnegie Corporation of New York",
    sourceUrl: "https://www.carnegie.org/"
  },
  {
    id: "nightingale-start",
    person: "Florence Nightingale",
    role: "看護改革者 / 統計家",
    initials: "FN",
    category: "resilience",
    accent: "#bd6448",
    quote: "I attribute my success to this: I never gave or took any excuse.",
    translation: "言い訳を受け入れず、自分にも許さない。",
    bio: "看護の近代化と医療統計の活用で知られる改革者。現場の課題を観察し、制度と実務の両方を変えた。",
    action: "今日の言い訳を1つ、次の行動に言い換える。",
    sourceTitle: "Florence Nightingale Museum",
    sourceUrl: "https://www.florence-nightingale.co.uk/"
  },
  {
    id: "da-vinci-simple",
    person: "Leonardo da Vinci",
    role: "芸術家 / 発明家",
    initials: "LD",
    category: "craft",
    accent: "#315f8d",
    quote: "Simplicity is the ultimate sophistication.",
    translation: "本当に洗練されたものは、余計なものが少ない。",
    bio: "芸術、科学、工学にまたがって観察と試作を重ねた人物。複雑な世界を見つめながら、本質をつかむ姿勢が現代にも通じる。",
    action: "自分の作品や計画から、余計な要素を1つ削る。",
    sourceTitle: "The Royal Collection Trust: Leonardo da Vinci",
    sourceUrl: "https://www.rct.uk/collection/themes/exhibitions/leonardo-da-vinci-a-life-in-drawing"
  },
  {
    id: "walker-promoted-myself",
    person: "Madam C. J. Walker",
    role: "起業家 / 慈善家",
    initials: "MW",
    category: "startup",
    accent: "#17665d",
    quote: "I promoted myself into the business.",
    translation: "誰かに選ばれるのを待たず、自分で事業の場へ進む。",
    bio: "ヘアケア事業を築き、米国初期の自力で成功した女性起業家として知られる人物。厳しい環境から出発し、販売員の育成や女性の経済的自立にも力を注いだ。",
    action: "今日は、誰かの許可を待っていることを1つ自分から始める。",
    sourceTitle: "National Women's History Museum: Madam C. J. Walker",
    sourceUrl: "https://www.womenshistory.org/education-resources/biographies/madam-cj-walker"
  },
  {
    id: "lauder-selling",
    person: "Estée Lauder",
    role: "Estée Lauder 創業者",
    initials: "EL",
    category: "business",
    accent: "#bd6448",
    quote: "If I believe in something, I sell it, and I sell it hard.",
    translation: "本当に信じるものなら、遠慮せず強く届ける。",
    bio: "台所で作ったクリームから世界的な化粧品企業を築いた起業家。商品そのものだけでなく、体験、接客、口コミを通じて価値を広げた。",
    action: "自分が本当に良いと思うものを、今日は1人に具体的に伝える。",
    sourceTitle: "The Estée Lauder Companies: Our Heritage",
    sourceUrl: "https://www.elcompanies.com/en/who-we-are/our-history"
  },
  {
    id: "disney-begin-doing",
    person: "Walt Disney",
    role: "Disney 創業者",
    initials: "WD",
    category: "craft",
    accent: "#315f8d",
    quote: "Quit talking and begin doing.",
    translation: "話し続けるより、まず動き始める。",
    bio: "アニメーション、映画、テーマパークを通じて新しい娯楽体験を作った起業家。構想を語るだけでなく、試作と改善を重ねて世界観を形にした。",
    action: "説明や計画を一度止めて、目に見える小さな成果物を1つ作る。",
    sourceTitle: "D23: Walt Disney Biography",
    sourceUrl: "https://d23.com/walt-disney-legend/"
  },
  {
    id: "knight-keep-going",
    person: "Phil Knight",
    role: "Nike 共同創業者",
    initials: "PK",
    category: "startup",
    accent: "#b6842f",
    quote: "Just keep going. Don't stop.",
    translation: "進み続ける。止まらない。",
    bio: "Blue Ribbon SportsからNikeを築いた起業家。著書『Shoe Dog』では、資金繰り、取引、訴訟、迷いを抱えながら前へ進む創業期が描かれている。",
    action: "今日の作業を止めそうになったら、あと10分だけ続ける。",
    sourceTitle: "Simon & Schuster: Shoe Dog by Phil Knight",
    sourceUrl: "https://www.simonandschuster.com/books/Shoe-Dog/Phil-Knight/9781501135927"
  },
  {
    id: "blakely-failure",
    person: "Sara Blakely",
    role: "Spanx 創業者",
    initials: "SB",
    category: "resilience",
    accent: "#bd6448",
    quote: "Failure is not trying.",
    translation: "本当の失敗は、試さないこと。",
    bio: "Spanxを創業し、既存の下着市場に新しい選択肢を作った起業家。失敗を避けるより、試して学ぶ姿勢を多くのインタビューで語っている。",
    action: "結果が読めないことを1つ、小さく試して記録する。",
    sourceTitle: "Spanx: Sara Blakely Founder Story",
    sourceUrl: "https://spanx.com/pages/about-us"
  },
  {
    id: "schultz-human-connection",
    person: "Howard Schultz",
    role: "Starbucks 元CEO",
    initials: "HS",
    category: "business",
    accent: "#17665d",
    quote: "Great companies are built one person at a time.",
    translation: "大きな会社も、結局は1人ずつとの信頼から作られる。",
    bio: "Starbucksを世界的ブランドに育てた経営者。コーヒーだけでなく、店舗体験、従業員、地域とのつながりを事業の中心に置いた。",
    action: "今日関わる1人に、いつもより丁寧な一言を添える。",
    sourceTitle: "Starbucks Stories: Howard Schultz",
    sourceUrl: "https://stories.starbucks.com/leadership/howard-schultz/"
  }
];
